Assets/Scenes/SampleScene.unity
Assets/Scripts/HenryController.cs

henry now waits between movements and walks off into the woods to disappear.

Updated henrys behavior

---

Assets/Scripts/Reaction.cs

Added a sphere as a prefab and attached a script "reaction" which detects the collided object.

Reaction Script

---

Assets/Scripts/HenryController.cs
Assets/Scripts/Reaction.cs
Assets/Scripts/ThrowObject.cs

Made few changes in "HenryController"(removed  "OnTriggerEnter" function and added distance collector so that if the player is in the range then it will be get caught by Henry) and added a function to change the color of Henry and stop him temporarily when it is collided with sphere.

Henrycontroller

---

Assets/Scenes/Campground.unity
Assets/Scripts/BananaTrap.cs
Assets/Scripts/BananaTrap.cs.meta
Assets/Scripts/HenryController.cs
Assets/Scripts/Player.cs
Assets/prefab/bananaTrap.prefab
Assets/prefab/bananaTrap.prefab.meta

their was an issue with merging the banana trap fixed it

fixed issue banana trap works.

---

Assets/Art Assets/Characters/BipedalRaccoon/raccoonAnimationController.controller
Assets/Art Assets/Characters/Henry/henryAnimationController.controller
Assets/Scenes/Campground.unity
Assets/Scripts/HenryController.cs
Assets/Scripts/Player.cs

added animations to henry and the raccoon.

Animation v3

---

Assets/Scenes/Campground.unity
Assets/Scripts/Item Interaction Scripts/StackCollectables.cs
Assets/Scripts/Reaction.cs

added a third food the tomato that will be harder to get since its in henrys patrol path. also fixed tomato throwing tag to detect the ground.

added third food and did some fixes

---

Assets/Scripts/BananaTrap.cs
Assets/Scripts/HenryController.cs
Assets/Scripts/Reaction.cs

allows the banana trap to make henry fall

committing Erajs work

---

Assets/Art Assets/HouseAssets/HouseParts/Door/DoorAnimatorController.controller
Assets/Scenes/Campground.unity
Assets/Scenes/House.unity
Assets/Scripts/GameInput.cs
Assets/prefab/HouseParts/Door/Door.prefab

fixed issue with player not being able to jump.
fixed issue with player not being able to collide with certain areas Reimplemented animation for door.

Fixed many issues.

---

Assets/Scripts/FamilyMembers/FamilyPatrolPoints.cs
Assets/Scripts/FamilyMembers/FamilyStateMachine/EmilyActivatedState.cs
Assets/Scripts/FamilyMembers/FamilyStateMachine/EmilyActivatedState.cs.meta
Assets/Scripts/FamilyMembers/FamilyStateMachine/FamilyStateMachine.cs
Assets/Scripts/FamilyMembers/Henry/EmilyController.cs
Assets/Scripts/FamilyMembers/Henry/EmilyController.cs.meta

added scripts for emilys attack and controller.

Scripts For Emily

---

Assets/Scripts/CharacterScripts/PlayerScripts/PlayerRunner.cs

Added a hiding function in player running script by which Player and turn invisible while he is near the objects with tag"hide" by clicking f button on keyboard.

cupboard & trash hiding

---

Assets/prefab/HouseParts/Door/Door.prefab
Assets/prefab/Screens/canvas.prefab
Assets/prefab/furniturePrefab/Cabinet.prefab
Assets/prefab/furniturePrefab/WashingMachine.prefab

- re added the interaction prompt under canvas
- changed some of the text so it was more clear how to interact

Re added the Interaction prompt

---

Assets/Scenes/Campground.unity
Assets/Scenes/House.unity

- for some reason level changes didnt get changed. changed them so they could be main

Fixed commit issue

---

Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/AirborneStates/PlayerJumpingState.cs
Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/GroundedStates/Moving/PlayerRunningState.cs
Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/GroundedStates/Moving/PlayerWalkingState.cs
Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/GroundedStates/PlayerIdlingState.cs

- manually reset trigger on exit to fix transition bug.

Fixed transition bug

---

Assets/Art Assets/Characters/BipedalRaccoon/raccoonAnimationController.controller
Assets/Art Assets/Characters/Henry/henryAnimationController.controller
Assets/Art Assets/Characters/Henry/henryFall.anim
Assets/Art Assets/Characters/Henry/henryFall.anim.meta
Assets/Art Assets/Characters/Henry/henryThrowing.anim
Assets/Art Assets/Characters/Henry/henryThrowing.anim.meta
Assets/Scripts/FamilyMembers/FamilyStateMachine/FamilyFreezeState.cs
Assets/Scripts/FamilyMembers/FamilyStateMachine/FamilyPatrolState.cs
Assets/Scripts/FamilyMembers/FamilyStateMachine/HenryActivatedState.cs
Assets/prefab/FamilyMembers/henry.prefab

- henry animator reworked
- henry now uses throw animation to throw the tool
- henry now uses slip and fall animation

Adding henrys animations

---

Assets/Scenes/House.unity
Assets/prefab/FamilyMembers/henry.prefab

- fixed the collision issue on one of the washing machines
- fixed emily's and henry's missing fov collision with interactableObstructions

Fixed Issues related to washing machine

---

Assets/Scenes/House.unity
Assets/Scripts/FamilyMembers/FamilyStateMachine/BryanStateMachine/BryanAttackState.cs
Assets/Scripts/KatanaDamage.cs

-  added the testing washing machine back (will remove later) in and guard point
-  added the ability to toggle when katana damages so that it only hurts when bryan is actually attacking

Added Activator back in and changed Katana

---

Assets/Scenes/Campground.unity
Assets/Scenes/House.unity
Assets/prefab/player.prefab

- Made cameras between levels more similar
- fixed character jitter issue on house level caused by camera looking at/following the racoons model
- fixed campground level camera pointing to the side of the character when level starts

Fixed Two camera issues

---

Assets/Art Assets/Characters/Emily/emilyAnimationController.controller
Assets/Art Assets/Characters/Emily/emilyAnimationController.controller.meta
Assets/Art Assets/Characters/Emily/emilyCharge.anim
Assets/Art Assets/Characters/Emily/emilyCharge.anim.meta
Assets/Scenes/House.unity
Assets/Scripts/FamilyMembers/FamilyStateMachine/EmilyChargeState.cs

- created a new animation controller for emily separate from henry
- implement the charging animation provided by dylan

Added emilys charge

---

Assets/Scripts/FamilyMembers/FamilyStateMachine/FamilyPatrolState.cs
Assets/Scripts/FamilyMembers/FamilyStateMachine/FamilySearchState.cs

- fixed the enemy getting stuck when going into search state
- fixed enemies not correctly transitioning from search state to patrol state

Fixed Two Animation bugs

---

Assets/Art Assets/HouseAssets/HouseParts/Corner/InsideCorner Variant 1.mat
Assets/Art Assets/HouseAssets/HouseParts/Corner/InsideCorner Variant 1.mat.meta
Assets/Scenes/Campground.unity
Assets/Scenes/House.unity
Assets/prefab/Screens/canvas.prefab
Assets/prefab/furniturePrefab/Chair.prefab

- made the chair collider two box collider instead of mesh collider so you didnt need to directly face a leg
- fixed some of the walls in bryans room being rotated the wrong way
- moved the Front door so its more in center
- create a variant for inside corner
- henrys patrol now works again
- removed the </b> from the tutorial text that include them
- made it so you no longer fall through the trash can
- edited the prompt text so it doesn't start with New Text

Minor fixes

---

Assets/Scenes/House.unity

- Fixed Alice not having activation music

Fixed a bugs i noticed

---

Assets/Scenes/Campground.unity
Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/GroundedStates/Moving/PlayerRunningState.cs
Assets/Scripts/CharacterScripts/PlayerScripts/StateMachines/Movement/States/PlayerMovementState.cs
Assets/Scripts/HideOnCollide.cs

- Fixed bug that prevented player from fall when sprinting
- assigned the correct script to disable player movement
- made it so henrys hammers dont prevent hiding
- Changed hide on collide to change the racoons layer so it is no longer targeted

Fixed Running state bug and HideOnCollision now works

---

Assets/Scripts/Throw/Shuriken.cs

Shuriken now stuns

---

Assets/Scenes/House.unity

Added Some more food and furniture

Added Some more food and furniture
